apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-demo
  template:
    metadata:
      labels:
        app: html-demo
    spec:
      containers:
      - name: html
        image: localhost/html-demo:latest
        ports:
        - containerPort: 80

