name: CI/CD Pipeline

on:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  IMAGE_NAME: adrianocortes/argocd
  K8S_MANIFEST_PATH: k8s/deployment.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: $IMAGE_NAME.*|image: $IMAGE_NAME:$IMAGE_TAG|" $K8S_MANIFEST_PATH

    - name: Commit and push manifest
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -am "Update image tag to $IMAGE_TAG"
        git push

